
spring:
    profiles: local
spark:
  master: local
  executor:
    memory: 1g
  cassandra:
    connection:
      host: 127.1.1.1
s3:
  bucket:
    name: test-bucket-1
  url: "s3://peoplenet-spark-poc-data/data/*"
